//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsGator.Install.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tasks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tasks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsGator.Install.Resources.Tasks", typeof(Tasks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding solution to the farm: {0}.
        /// </summary>
        public static string TaskDetails_AddSolution {
            get {
                return ResourceManager.GetString("TaskDetails_AddSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution is not already added to the farm: {0}.
        /// </summary>
        public static string TaskDetails_AddSolution_CheckIfExists {
            get {
                return ResourceManager.GetString("TaskDetails_AddSolution_CheckIfExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution file exists: {0}.
        /// </summary>
        public static string TaskDetails_AddSolution_CheckPath {
            get {
                return ResourceManager.GetString("TaskDetails_AddSolution_CheckPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution successfully added to the farm: {0}.
        /// </summary>
        public static string TaskDetails_AddSolution_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_AddSolution_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution was added to the farm: {0}.
        /// </summary>
        public static string TaskDetails_AddSolution_EnsureAdded {
            get {
                return ResourceManager.GetString("TaskDetails_AddSolution_EnsureAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying application bin content..
        /// </summary>
        public static string TaskDetails_CopyAppBin {
            get {
                return ResourceManager.GetString("TaskDetails_CopyAppBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying application bin content complete..
        /// </summary>
        public static string TaskDetails_CopyAppBinComplete {
            get {
                return ResourceManager.GetString("TaskDetails_CopyAppBinComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying application bin content on {0}..
        /// </summary>
        public static string TaskDetails_CopyAppBinOn {
            get {
                return ResourceManager.GetString("TaskDetails_CopyAppBinOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying application bin content complete on {0}..
        /// </summary>
        public static string TaskDetails_CopyAppBinOnComplete {
            get {
                return ResourceManager.GetString("TaskDetails_CopyAppBinOnComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution is not already deployed to the farm: {0}.
        /// </summary>
        public static string TaskDetails_DeploySolution_CheckIfDeployed {
            get {
                return ResourceManager.GetString("TaskDetails_DeploySolution_CheckIfDeployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution is on the farm: {0}.
        /// </summary>
        public static string TaskDetails_DeploySolution_CheckIfExists {
            get {
                return ResourceManager.GetString("TaskDetails_DeploySolution_CheckIfExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution successfully deployed to the farm: {0}.
        /// </summary>
        public static string TaskDetails_DeploySolution_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_DeploySolution_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying solution to the farm: {0}.
        /// </summary>
        public static string TaskDetails_DeploySolution_DeployingToFarm {
            get {
                return ResourceManager.GetString("TaskDetails_DeploySolution_DeployingToFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling just-in-time debugger..
        /// </summary>
        public static string TaskDetails_DisableDebugger {
            get {
                return ResourceManager.GetString("TaskDetails_DisableDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling just-in-time debugger complete..
        /// </summary>
        public static string TaskDetails_DisableDebugger_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_DisableDebugger_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling features..
        /// </summary>
        public static string TaskDetails_DisableFeatures {
            get {
                return ResourceManager.GetString("TaskDetails_DisableFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling features complete..
        /// </summary>
        public static string TaskDetails_DisableFeatures_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_DisableFeatures_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling Sitrion Social jobs..
        /// </summary>
        public static string TaskDetails_DisableJobs {
            get {
                return ResourceManager.GetString("TaskDetails_DisableJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling Sitrion Social jobs complete..
        /// </summary>
        public static string TaskDetails_DisableJobs_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_DisableJobs_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling user profile job..
        /// </summary>
        public static string TaskDetails_DisableUserProfileJob {
            get {
                return ResourceManager.GetString("TaskDetails_DisableUserProfileJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling user profile job complete..
        /// </summary>
        public static string TaskDetails_DisableUserProfileJob_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_DisableUserProfileJob_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling web applications..
        /// </summary>
        public static string TaskDetails_DisableWebApps {
            get {
                return ResourceManager.GetString("TaskDetails_DisableWebApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling web applications complete..
        /// </summary>
        public static string TaskDetails_DisableWebAppsComplete {
            get {
                return ResourceManager.GetString("TaskDetails_DisableWebAppsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling web applications on {0}..
        /// </summary>
        public static string TaskDetails_DisableWebAppsOn {
            get {
                return ResourceManager.GetString("TaskDetails_DisableWebAppsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling web applications complete on {0}..
        /// </summary>
        public static string TaskDetails_DisableWebAppsOnComplete {
            get {
                return ResourceManager.GetString("TaskDetails_DisableWebAppsOnComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling just-in-time debugger..
        /// </summary>
        public static string TaskDetails_EnableDebugger {
            get {
                return ResourceManager.GetString("TaskDetails_EnableDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling just-in-time debugger complete..
        /// </summary>
        public static string TaskDetails_EnableDebugger_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_EnableDebugger_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Sitrion Social jobs..
        /// </summary>
        public static string TaskDetails_EnableJobs {
            get {
                return ResourceManager.GetString("TaskDetails_EnableJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Sitrion Social jobs complete..
        /// </summary>
        public static string TaskDetails_EnableJobs_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_EnableJobs_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling user profile job..
        /// </summary>
        public static string TaskDetails_EnableUserProfileJob {
            get {
                return ResourceManager.GetString("TaskDetails_EnableUserProfileJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling user profile job complete..
        /// </summary>
        public static string TaskDetails_EnableUserProfileJob_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_EnableUserProfileJob_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling web applications..
        /// </summary>
        public static string TaskDetails_EnableWebApps {
            get {
                return ResourceManager.GetString("TaskDetails_EnableWebApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling web applications complete..
        /// </summary>
        public static string TaskDetails_EnableWebAppsComplete {
            get {
                return ResourceManager.GetString("TaskDetails_EnableWebAppsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling web applications on {0}..
        /// </summary>
        public static string TaskDetails_EnableWebAppsOn {
            get {
                return ResourceManager.GetString("TaskDetails_EnableWebAppsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling web applications complete on {0}..
        /// </summary>
        public static string TaskDetails_EnableWebAppsOnComplete {
            get {
                return ResourceManager.GetString("TaskDetails_EnableWebAppsOnComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring web application pools..
        /// </summary>
        public static string TaskDetails_EnsureWebApps {
            get {
                return ResourceManager.GetString("TaskDetails_EnsureWebApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring web application pools complete..
        /// </summary>
        public static string TaskDetails_EnsureWebAppsComplete {
            get {
                return ResourceManager.GetString("TaskDetails_EnsureWebAppsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring web application pools on {0}..
        /// </summary>
        public static string TaskDetails_EnsureWebAppsOn {
            get {
                return ResourceManager.GetString("TaskDetails_EnsureWebAppsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring web application pools complete on {0}..
        /// </summary>
        public static string TaskDetails_EnsureWebAppsOnComplete {
            get {
                return ResourceManager.GetString("TaskDetails_EnsureWebAppsOnComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SharePoint Admin service jobs..
        /// </summary>
        public static string TaskDetails_ExecuteAdminJobs {
            get {
                return ResourceManager.GetString("TaskDetails_ExecuteAdminJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SharePonit Admin service jobs complete..
        /// </summary>
        public static string TaskDetails_ExecuteAdminJobs_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_ExecuteAdminJobs_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SharePonit Admin service jobs complete on {0}..
        /// </summary>
        public static string TaskDetails_ExecuteAdminJobs_CompleteOn {
            get {
                return ResourceManager.GetString("TaskDetails_ExecuteAdminJobs_CompleteOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SharePoint Admin service jobs on {0}..
        /// </summary>
        public static string TaskDetails_ExecuteAdminJobsOn {
            get {
                return ResourceManager.GetString("TaskDetails_ExecuteAdminJobsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SharePoint Timer Service Recycle job..
        /// </summary>
        public static string TaskDetails_ExecuteTimerServiceJob {
            get {
                return ResourceManager.GetString("TaskDetails_ExecuteTimerServiceJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SharePoint Timer Service Recycle job complete..
        /// </summary>
        public static string TaskDetails_ExecuteTimerServiceJobComplete {
            get {
                return ResourceManager.GetString("TaskDetails_ExecuteTimerServiceJobComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Lookout on My Site host..
        /// </summary>
        public static string TaskDetails_MySiteEnableLookout {
            get {
                return ResourceManager.GetString("TaskDetails_MySiteEnableLookout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Lookout on My Site host complete..
        /// </summary>
        public static string TaskDetails_MySiteEnableLookout_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_MySiteEnableLookout_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing web parts on My Site Newsfeed page..
        /// </summary>
        public static string TaskDetails_MySiteNewsFeedPage {
            get {
                return ResourceManager.GetString("TaskDetails_MySiteNewsFeedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing web parts on My Site Newsfeed page complete..
        /// </summary>
        public static string TaskDetails_MySiteNewsFeedPage_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_MySiteNewsFeedPage_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Lookout as home page for My Site host..
        /// </summary>
        public static string TaskDetails_MySiteSetLookoutHomePage {
            get {
                return ResourceManager.GetString("TaskDetails_MySiteSetLookoutHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Lookout as home page for My Site host complete..
        /// </summary>
        public static string TaskDetails_MySiteSetLookoutHomePage_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_MySiteSetLookoutHomePage_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Sitrion Social web parts feature on My Site host..
        /// </summary>
        public static string TaskDetails_MySiteWebParts {
            get {
                return ResourceManager.GetString("TaskDetails_MySiteWebParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Sitrion Social web parts feature on My Site host complete..
        /// </summary>
        public static string TaskDetails_MySiteWebParts_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_MySiteWebParts_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisioning service application: {0}.
        /// </summary>
        public static string TaskDetails_ProvisionServiceApplication {
            get {
                return ResourceManager.GetString("TaskDetails_ProvisionServiceApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisioning service application complete: {0}.
        /// </summary>
        public static string TaskDetails_ProvisionServiceApplication_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_ProvisionServiceApplication_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivating features..
        /// </summary>
        public static string TaskDetails_ReactivateFeatures {
            get {
                return ResourceManager.GetString("TaskDetails_ReactivateFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivating features complete..
        /// </summary>
        public static string TaskDetails_ReactivateFeatures_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_ReactivateFeatures_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing orphaned features..
        /// </summary>
        public static string TaskDetails_RemoveOrphanedFeatures {
            get {
                return ResourceManager.GetString("TaskDetails_RemoveOrphanedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing orphaned features complete..
        /// </summary>
        public static string TaskDetails_RemoveOrphanedFeatures_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_RemoveOrphanedFeatures_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing service application: {0}.
        /// </summary>
        public static string TaskDetails_RemoveServiceApplication {
            get {
                return ResourceManager.GetString("TaskDetails_RemoveServiceApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing service application complete: {0}.
        /// </summary>
        public static string TaskDetails_RemoveServiceApplication_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_RemoveServiceApplication_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing solution from the farm: {0}.
        /// </summary>
        public static string TaskDetails_RemoveSolution {
            get {
                return ResourceManager.GetString("TaskDetails_RemoveSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution is on the farm: {0}.
        /// </summary>
        public static string TaskDetails_RemoveSolution_CheckIfExists {
            get {
                return ResourceManager.GetString("TaskDetails_RemoveSolution_CheckIfExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution successfully removed from the farm: {0}.
        /// </summary>
        public static string TaskDetails_RemoveSolution_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_RemoveSolution_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution was removed from the farm: {0}.
        /// </summary>
        public static string TaskDetails_RemoveSolution_EnsureRemoved {
            get {
                return ResourceManager.GetString("TaskDetails_RemoveSolution_EnsureRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution is not deployed: {0}.
        /// </summary>
        public static string TaskDetails_RemoveSolution_EnsureRetracted {
            get {
                return ResourceManager.GetString("TaskDetails_RemoveSolution_EnsureRetracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting SharePoint Services.
        /// </summary>
        public static string TaskDetails_RestartServices {
            get {
                return ResourceManager.GetString("TaskDetails_RestartServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating Sitrion Social Installer Jobs farm feature..
        /// </summary>
        public static string TaskDetails_RestartServices_ActivatingFarmFeature {
            get {
                return ResourceManager.GetString("TaskDetails_RestartServices_ActivatingFarmFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting SharePoint Services Complete.
        /// </summary>
        public static string TaskDetails_RestartServices_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_RestartServices_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Services Job Completed on {0}.
        /// </summary>
        public static string TaskDetails_RestartServices_JobComplete {
            get {
                return ResourceManager.GetString("TaskDetails_RestartServices_JobComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Restart Services Job on {0}.
        /// </summary>
        public static string TaskDetails_RestartServices_StartingJob {
            get {
                return ResourceManager.GetString("TaskDetails_RestartServices_StartingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Job on {0}.
        /// </summary>
        public static string TaskDetails_StartingJob {
            get {
                return ResourceManager.GetString("TaskDetails_StartingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating features..
        /// </summary>
        public static string TaskDetails_UpdateFeatures {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating features complete..
        /// </summary>
        public static string TaskDetails_UpdateFeatures_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateFeatures_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating service application: {0}.
        /// </summary>
        public static string TaskDetails_UpdateServiceApplication {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateServiceApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating service application complete: {0}.
        /// </summary>
        public static string TaskDetails_UpdateServiceApplication_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateServiceApplication_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating solution on the farm: {0}.
        /// </summary>
        public static string TaskDetails_UpdateSolution {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding solution to the farm: {0}.
        /// </summary>
        public static string TaskDetails_UpdateSolution_AddSolution {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateSolution_AddSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution file exists: {0}.
        /// </summary>
        public static string TaskDetails_UpdateSolution_CheckPath {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateSolution_CheckPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution was successfully updated on the farm: {0}.
        /// </summary>
        public static string TaskDetails_UpdateSolution_Complete {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateSolution_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying solution to the farm: {0}.
        /// </summary>
        public static string TaskDetails_UpdateSolution_DeployingToFarm {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateSolution_DeployingToFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution is on the farm: {0}.
        /// </summary>
        public static string TaskDetails_UpdateSolution_EnsureOnFarm {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateSolution_EnsureOnFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring solution was updated on the farm: {0}.
        /// </summary>
        public static string TaskDetails_UpdateSolution_EnsuringUpdated {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateSolution_EnsuringUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution is not deployed, removing existing solution from the farm: {0}.
        /// </summary>
        public static string TaskDetails_UpdateSolution_NotDeployed {
            get {
                return ResourceManager.GetString("TaskDetails_UpdateSolution_NotDeployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Failed, Trying Again..
        /// </summary>
        public static string TaskFailed_Retrying {
            get {
                return ResourceManager.GetString("TaskFailed_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SharePoint Solution: {0}.
        /// </summary>
        public static string TaskName_AddSolution {
            get {
                return ResourceManager.GetString("TaskName_AddSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Application Bin Content.
        /// </summary>
        public static string TaskName_CopyAppBin {
            get {
                return ResourceManager.GetString("TaskName_CopyAppBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy SharePoint Solution: {0}.
        /// </summary>
        public static string TaskName_DeploySolution {
            get {
                return ResourceManager.GetString("TaskName_DeploySolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Just-In-Time Debugger.
        /// </summary>
        public static string TaskName_DisableDebugger {
            get {
                return ResourceManager.GetString("TaskName_DisableDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Features.
        /// </summary>
        public static string TaskName_DisableFeatures {
            get {
                return ResourceManager.GetString("TaskName_DisableFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Sitrion Social Jobs.
        /// </summary>
        public static string TaskName_DisableJobs {
            get {
                return ResourceManager.GetString("TaskName_DisableJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable User Profile Job.
        /// </summary>
        public static string TaskName_DisableUserProfileJob {
            get {
                return ResourceManager.GetString("TaskName_DisableUserProfileJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Web Applications.
        /// </summary>
        public static string TaskName_DisableWebApps {
            get {
                return ResourceManager.GetString("TaskName_DisableWebApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Just-In-Time Debugger.
        /// </summary>
        public static string TaskName_EnableDebugger {
            get {
                return ResourceManager.GetString("TaskName_EnableDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sitrion Social Jobs.
        /// </summary>
        public static string TaskName_EnableJobs {
            get {
                return ResourceManager.GetString("TaskName_EnableJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable User Profile Job.
        /// </summary>
        public static string TaskName_EnableUserProfileJob {
            get {
                return ResourceManager.GetString("TaskName_EnableUserProfileJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Web Applications.
        /// </summary>
        public static string TaskName_EnableWebApps {
            get {
                return ResourceManager.GetString("TaskName_EnableWebApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure Web Application Pools.
        /// </summary>
        public static string TaskName_EnsureWebApps {
            get {
                return ResourceManager.GetString("TaskName_EnsureWebApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute SharePoint Admin Service Job.
        /// </summary>
        public static string TaskName_ExecuteAdminJobs {
            get {
                return ResourceManager.GetString("TaskName_ExecuteAdminJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute SharePoint Admin Service Job on {0}.
        /// </summary>
        public static string TaskName_ExecuteAdminJobsOn {
            get {
                return ResourceManager.GetString("TaskName_ExecuteAdminJobsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute SharePoint Timer Service Recycle Job.
        /// </summary>
        public static string TaskName_ExecuteTimerServiceJob {
            get {
                return ResourceManager.GetString("TaskName_ExecuteTimerServiceJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Lookout on My Site Host.
        /// </summary>
        public static string TaskName_MySiteEnableLookout {
            get {
                return ResourceManager.GetString("TaskName_MySiteEnableLookout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Web Parts on My Site Newsfeed Page.
        /// </summary>
        public static string TaskName_MySiteNewsFeedPage {
            get {
                return ResourceManager.GetString("TaskName_MySiteNewsFeedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Lookout as Home Page for My Site Host.
        /// </summary>
        public static string TaskName_MySiteSetLookoutHomePage {
            get {
                return ResourceManager.GetString("TaskName_MySiteSetLookoutHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sitrion Social Web Parts Feature on My Site Host.
        /// </summary>
        public static string TaskName_MySiteWebParts {
            get {
                return ResourceManager.GetString("TaskName_MySiteWebParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision Service Application: {0}.
        /// </summary>
        public static string TaskName_ProvisionServiceApplication {
            get {
                return ResourceManager.GetString("TaskName_ProvisionServiceApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivate Features.
        /// </summary>
        public static string TaskName_ReactivateFeatures {
            get {
                return ResourceManager.GetString("TaskName_ReactivateFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Orphaned Features.
        /// </summary>
        public static string TaskName_RemoveOrphanedFeatures {
            get {
                return ResourceManager.GetString("TaskName_RemoveOrphanedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Service Application: {0}.
        /// </summary>
        public static string TaskName_RemoveServiceApplication {
            get {
                return ResourceManager.GetString("TaskName_RemoveServiceApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove SharePoint Solution: {0}.
        /// </summary>
        public static string TaskName_RemoveSolution {
            get {
                return ResourceManager.GetString("TaskName_RemoveSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart SharePoint Services.
        /// </summary>
        public static string TaskName_RestartServices {
            get {
                return ResourceManager.GetString("TaskName_RestartServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Features.
        /// </summary>
        public static string TaskName_UpdateFeatures {
            get {
                return ResourceManager.GetString("TaskName_UpdateFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Service Application: {0}.
        /// </summary>
        public static string TaskName_UpdateServiceApplication {
            get {
                return ResourceManager.GetString("TaskName_UpdateServiceApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update SharePoint Solution: {0}.
        /// </summary>
        public static string TaskName_UpdateSolution {
            get {
                return ResourceManager.GetString("TaskName_UpdateSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Task List.
        /// </summary>
        public static string TaskOperations_BuildingList {
            get {
                return ResourceManager.GetString("TaskOperations_BuildingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Task List Complete.
        /// </summary>
        public static string TaskOperations_BuildingList_Complete {
            get {
                return ResourceManager.GetString("TaskOperations_BuildingList_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Tasks.
        /// </summary>
        public static string TaskOperations_RunningTasks {
            get {
                return ResourceManager.GetString("TaskOperations_RunningTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Tasks Complete.
        /// </summary>
        public static string TaskOperations_RunningTasks_Complete {
            get {
                return ResourceManager.GetString("TaskOperations_RunningTasks_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Task: {0}.
        /// </summary>
        public static string TaskOperations_RunTask {
            get {
                return ResourceManager.GetString("TaskOperations_RunTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Complete: {0}.
        /// </summary>
        public static string TaskOperations_RunTask_Complete {
            get {
                return ResourceManager.GetString("TaskOperations_RunTask_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Failed to Complete: {0}.  To retry this task manually from the Sitrion Social Management Shell, use the following command: \r\n{1}.
        /// </summary>
        public static string TaskRunner_CompleteFailed {
            get {
                return ResourceManager.GetString("TaskRunner_CompleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Completed Successfully: {0}.
        /// </summary>
        public static string TaskRunner_CompleteSuccess {
            get {
                return ResourceManager.GetString("TaskRunner_CompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Task: {0}.
        /// </summary>
        public static string TaskRunner_StartingTask {
            get {
                return ResourceManager.GetString("TaskRunner_StartingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &quot;{0}&quot; operation time: {1} ms.
        /// </summary>
        public static string TaskRunner_Time {
            get {
                return ResourceManager.GetString("TaskRunner_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Timed Out: {0}.
        /// </summary>
        public static string TaskRunner_Timeout {
            get {
                return ResourceManager.GetString("TaskRunner_Timeout", resourceCulture);
            }
        }
    }
}
