//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMLiveWebParts {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class FancyDisplayForm {
        
        protected global::System.Web.UI.WebControls.Button btnCancel1;
        
        protected global::System.Web.UI.WebControls.Label lblItemTitle;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divQuickDetailsContent;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divShowQuickDetailsHeader;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divShowQuickDetailsContent;
        
        protected global::System.Web.UI.HtmlControls.HtmlTableCell divQuickDetailsParent;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divNarrativeDetails;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divNarrativeDetailsContent;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divShowNarrativeDetailsHeader;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divShowNarrativeDetailsContent;
        
        protected global::System.Web.UI.HtmlControls.HtmlTableCell divNarrativeDetailsParent;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPeopleDetails;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPeopleContent;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPeopleShowAllHeader;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPeopleShowAllContent;
        
        protected global::System.Web.UI.HtmlControls.HtmlTableCell divPeopleDetailsParent;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDateDetails;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDatesContent;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDatesShowAllHeader;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDatesShowAllContent;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divShowAllDateDetails;
        
        protected global::System.Web.UI.HtmlControls.HtmlTableCell divDateDetailsParent;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divFancyDispFormAssociatedItemsContent;
        
        protected global::System.Web.UI.HtmlControls.HtmlTableCell divFancyDispFormParent;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divItemDetailParent;
        
        protected global::System.Web.UI.WebControls.Button btnCancel2;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divFancyDisplayForm;
        
        public static implicit operator global::System.Web.UI.TemplateControl(FancyDisplayForm target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel1() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancel1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancel1";
            @__ctrl.Text = "Close";
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblItemTitle() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblItemTitle = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblItemTitle";
            @__ctrl.CssClass = "dispFormFancyTitle";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivQuickDetailsContent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divQuickDetailsContent = @__ctrl;
            @__ctrl.ID = "divQuickDetailsContent";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormContent");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivShowQuickDetailsHeader() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divShowQuickDetailsHeader = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormExpandHeader");
            @__ctrl.ID = "divShowQuickDetailsHeader";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                            <span class=\"icon-plus-circle-2\"></" +
                        "span><span>show</span>\r\n                                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivShowQuickDetailsContent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divShowQuickDetailsContent = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormContent");
            @__ctrl.ID = "divShowQuickDetailsContent";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControldivQuickDetailsParent() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            this.divQuickDetailsParent = @__ctrl;
            @__ctrl.ID = "divQuickDetailsParent";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div id=\"divQuickDetailsHeader\" class=\"fancy-display-he" +
                        "ader\">\r\n                            <span>Quick Details</span>\r\n                " +
                        "        </div>\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldivQuickDetailsContent();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div style=\"width: 100%\">\r\n                            " +
                        "<table border=\"0\" style=\"width: 100%\">\r\n                                <tr>\r\n  " +
                        "                                  <td>\r\n                                        " +
                        ""));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControldivShowQuickDetailsHeader();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl3;
            @__ctrl3 = this.@__BuildControldivShowQuickDetailsContent();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                </tr" +
                        ">\r\n                            </table>\r\n                        </div>\r\n       " +
                        "             "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivNarrativeDetails() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divNarrativeDetails = @__ctrl;
            @__ctrl.ID = "divNarrativeDetails";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fancy-display-header");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            <span>Narrative Details</span>\r\n                   " +
                        "     "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivNarrativeDetailsContent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divNarrativeDetailsContent = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormContent");
            @__ctrl.ID = "divNarrativeDetailsContent";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivShowNarrativeDetailsHeader() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divShowNarrativeDetailsHeader = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormExpandHeader");
            @__ctrl.ID = "divShowNarrativeDetailsHeader";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                            <span class=\"icon-plus-circle-2\"></" +
                        "span><span>show</span>\r\n                                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivShowNarrativeDetailsContent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divShowNarrativeDetailsContent = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormContent");
            @__ctrl.ID = "divShowNarrativeDetailsContent";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControldivNarrativeDetailsParent() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            this.divNarrativeDetailsParent = @__ctrl;
            @__ctrl.ID = "divNarrativeDetailsParent";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldivNarrativeDetails();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControldivNarrativeDetailsContent();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div>\r\n                            <table border=\"0\" st" +
                        "yle=\"width: 100%\">\r\n                                <tr>\r\n                      " +
                        "              <td>\r\n                                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl3;
            @__ctrl3 = this.@__BuildControldivShowNarrativeDetailsHeader();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl4;
            @__ctrl4 = this.@__BuildControldivShowNarrativeDetailsContent();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                </tr" +
                        ">\r\n                            </table>\r\n                        </div>\r\n       " +
                        "             "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivPeopleDetails() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divPeopleDetails = @__ctrl;
            @__ctrl.ID = "divPeopleDetails";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fancy-display-header");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            <span>People</span>\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivPeopleContent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divPeopleContent = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormContent");
            @__ctrl.ID = "divPeopleContent";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivPeopleShowAllHeader() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divPeopleShowAllHeader = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormExpandHeader");
            @__ctrl.ID = "divPeopleShowAllHeader";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                            <span class=\"icon-plus-circle-2\"></" +
                        "span><span>show</span>\r\n                                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivPeopleShowAllContent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divPeopleShowAllContent = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormContent");
            @__ctrl.ID = "divPeopleShowAllContent";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControldivPeopleDetailsParent() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            this.divPeopleDetailsParent = @__ctrl;
            @__ctrl.ID = "divPeopleDetailsParent";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldivPeopleDetails();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControldivPeopleContent();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div>\r\n                            <table border=\"0\" st" +
                        "yle=\"width: 100%\">\r\n                                <tr>\r\n                      " +
                        "              <td>\r\n                                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl3;
            @__ctrl3 = this.@__BuildControldivPeopleShowAllHeader();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl4;
            @__ctrl4 = this.@__BuildControldivPeopleShowAllContent();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                </tr" +
                        ">\r\n                            </table>\r\n                        </div>\r\n       " +
                        "             "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivDateDetails() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divDateDetails = @__ctrl;
            @__ctrl.ID = "divDateDetails";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fancy-display-header");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            <span>Dates</span>\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivDatesContent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divDatesContent = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormContent");
            @__ctrl.ID = "divDatesContent";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivDatesShowAllHeader() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divDatesShowAllHeader = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormExpandHeader");
            @__ctrl.ID = "divDatesShowAllHeader";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                            <span class=\"icon-plus-circle-2\"></" +
                        "span><span>show</span>\r\n                                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivDatesShowAllContent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divDatesShowAllContent = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormContent");
            @__ctrl.ID = "divDatesShowAllContent";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivShowAllDateDetails() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divShowAllDateDetails = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormContent");
            @__ctrl.ID = "divShowAllDateDetails";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            <table border=\"0\" style=\"width: 100%\">\r\n           " +
                        "                     <tr>\r\n                                    <td>\r\n           " +
                        "                             "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldivDatesShowAllHeader();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControldivDatesShowAllContent();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </td>\r\n                                </tr" +
                        ">\r\n                            </table>\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControldivDateDetailsParent() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            this.divDateDetailsParent = @__ctrl;
            @__ctrl.ID = "divDateDetailsParent";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldivDateDetails();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControldivDatesContent();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl3;
            @__ctrl3 = this.@__BuildControldivShowAllDateDetails();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivFancyDispFormAssociatedItemsContent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divFancyDispFormAssociatedItemsContent = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "dispFormContent");
            @__ctrl.ID = "divFancyDispFormAssociatedItemsContent";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "color: #555555;");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControldivFancyDispFormParent() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            this.divFancyDispFormParent = @__ctrl;
            @__ctrl.ID = "divFancyDispFormParent";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div id=\"divFancyDispForm\" class=\"fancy-display-header\"" +
                        ">\r\n                            <span>Associated Items</span>\r\n                  " +
                        "      </div>\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldivFancyDispFormAssociatedItemsContent();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivItemDetailParent() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divItemDetailParent = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fancyDisplayForm dispFormContent");
            @__ctrl.ID = "divItemDetailParent";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "float: right; width: 100%;");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel2() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancel2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancel2";
            @__ctrl.Text = "Close";
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivFancyDisplayForm() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divFancyDisplayForm = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "fancy-display-form-wrapper");
            @__ctrl.ID = "divFancyDisplayForm";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "width: 100%");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    <div style=\"text-align: right; float: right;\">\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl1;
            @__ctrl1 = this.@__BuildControlbtnCancel1();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n\r\n    <div class=\"dispFormFancyTitle\">\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllblItemTitle();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n\r\n    <div class=\"fancyDisplayForm\" style=\"width: 100%; vertical-al" +
                        "ign: top;\">\r\n\r\n        <div id=\"first-table\">\r\n            <table border=\"0\" sty" +
                        "le=\"width: 100%\">\r\n                <tr>\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl3;
            @__ctrl3 = this.@__BuildControldivQuickDetailsParent();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </tr>\r\n                <tr>\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl4;
            @__ctrl4 = this.@__BuildControldivNarrativeDetailsParent();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </tr>\r\n            </table>\r\n        </div>\r\n        <div style" +
                        "=\"vertical-align: top; display: inline;\">\r\n            <table border=\"0\">\r\n     " +
                        "           <tr>\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl5;
            @__ctrl5 = this.@__BuildControldivPeopleDetailsParent();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </tr>\r\n                <tr>\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl6;
            @__ctrl6 = this.@__BuildControldivDateDetailsParent();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </tr>\r\n                <tr>\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl7;
            @__ctrl7 = this.@__BuildControldivFancyDispFormParent();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </tr>\r\n            </table>\r\n        </div>\r\n\r\n    </div>\r\n\r\n  " +
                        "  "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl8;
            @__ctrl8 = this.@__BuildControldivItemDetailParent();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    <div style=\"text-align: right; float: right;\">\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl9;
            @__ctrl9 = this.@__BuildControlbtnCancel2();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::EPMLiveWebParts.FancyDisplayForm @__ctrl) {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldivFancyDisplayForm();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n<style type=\"text/css\">\r\n    .fancy-display-form-wrapper {\r\n        font-fami" +
                    "ly: Open Sans Light !important;\r\n        color: #555555;\r\n        width: 100%;\r\n" +
                    "        height: 100%;\r\n        /*width: 900px;*/\r\n        /*min-width: 900px;*/\r" +
                    "\n    }\r\n\r\n    .fancyDisplayForm {\r\n        background-color: #ffffff;\r\n        v" +
                    "ertical-align: middle;\r\n        outline: none;\r\n        resize: none;\r\n        d" +
                    "isplay: inline-block;\r\n        -webkit-font-smoothing: antialiased;\r\n        -mo" +
                    "z-osx-font-smoothing: grayscale;\r\n        width: 100%;\r\n    }\r\n\r\n        .fancyD" +
                    "isplayForm #first-table {\r\n            vertical-align: top;\r\n            float: " +
                    "left;\r\n            margin-right: 20px;\r\n            width: 63.5%;\r\n        }\r\n\r\n" +
                    "    .fancy-display-header {\r\n        border-bottom: 1px solid #EEEEEE;\r\n        " +
                    "cursor: auto;\r\n        font-size: 1.4em;\r\n        padding-bottom: 5px;\r\n        " +
                    "padding-top: 5px;\r\n        font-family: Open Sans Regular !important;\r\n    }\r\n\r\n" +
                    "        .fancy-display-header span {\r\n            color: #555555;\r\n        }\r\n\r\n" +
                    "    .fancy-col-table {\r\n    }\r\n\r\n        .fancy-col-table tr td:first-child {\r\n " +
                    "           width: 175px;\r\n            font-family: Open Sans Regular !important;" +
                    "\r\n            vertical-align: middle;\r\n        }\r\n\r\n        .fancy-col-table tr " +
                    "td {\r\n            font-size: 1em;\r\n            padding-bottom: 5px;\r\n           " +
                    " width: 150px;\r\n        }\r\n\r\n    .fancyDisplayForm .dispFormContent {\r\n        d" +
                    "isplay: block;\r\n        width: 100%;\r\n        padding-top: 5px;\r\n    }\r\n\r\n    .f" +
                    "ancy-display-form-wrapper .dispFormExpandHeader {\r\n        cursor: pointer;\r\n   " +
                    "     display: inline-block;\r\n        padding-bottom: 5px;\r\n        color: #0090C" +
                    "A;\r\n        vertical-align: top;\r\n    }\r\n\r\n        .fancy-display-form-wrapper ." +
                    "dispFormExpandHeader span:first-child {\r\n            color: #0090CA;\r\n          " +
                    "  padding-right: 5px;\r\n            position: relative;\r\n            top: 1px;\r\n " +
                    "           font-size: .9em;\r\n        }\r\n\r\n    .fancy-display-form-wrapper .dispF" +
                    "ormFancyTitle {\r\n        display: inline-block;\r\n        padding-bottom: 5px;\r\n " +
                    "   }\r\n\r\n        .fancy-display-form-wrapper .dispFormFancyTitle span {\r\n        " +
                    "    font-size: 2em;\r\n        }\r\n\r\n    .fancy-display-form-wrapper .dispFormUserI" +
                    "mage {\r\n        fit-position: slice;\r\n        height: 22px;\r\n        text-align:" +
                    " center;\r\n        border-radius: 50%;\r\n        vertical-align: bottom;\r\n    }\r\n\r" +
                    "\n    .fancy-display-form-wrapper .dispFormExpandMore {\r\n        cursor: pointer;" +
                    "\r\n        display: inline-block;\r\n        color: #0090CA;\r\n        font-size: 12" +
                    "px;\r\n        padding-top: 7px;\r\n    }\r\n\r\n    .badge {\r\n        display: inline-b" +
                    "lock;\r\n        min-width: 14px;\r\n        padding: 2px 8px;\r\n        font-size: 1" +
                    "2px;\r\n        font-family: \"Open Sans Semi Bold\" !important;\r\n        color: #ff" +
                    "f;\r\n        line-height: 13px;\r\n        vertical-align: baseline;\r\n        white" +
                    "-space: nowrap;\r\n        text-align: center;\r\n        background-color: #999;\r\n " +
                    "       border-radius: 10px;\r\n    }\r\n\r\n        .badge:hover {\r\n            backgr" +
                    "ound-color: #0090CA;\r\n        }\r\n\r\n\r\n    /* Small devices */\r\n    @media (max-wi" +
                    "dth: 768px) {\r\n        .fancyDisplayForm #first-table {\r\n            float: none" +
                    ";\r\n        }\r\n\r\n        .fancyDisplayForm #first-table {\r\n            width: 100" +
                    "%;\r\n        }\r\n    }\r\n\r\n    .fancy-display-form-wrapper .slidingDiv {\r\n        w" +
                    "idth: 100%;\r\n        padding: 20px;\r\n        border: 1px thin black;\r\n        -w" +
                    "ebkit-box-shadow: 0px 3px 20px rgba(50, 50, 50, 0.8);\r\n        -moz-box-shadow: " +
                    "0px 3px 20px rgba(50, 50, 50, 0.8);\r\n        box-shadow: 0px 3px 20px rgba(50, 5" +
                    "0, 50, 0.8);\r\n        position: absolute;\r\n        width: 200px;\r\n        backgr" +
                    "ound-color: white;\r\n        text-align: left;\r\n        z-index: 100;\r\n    }\r\n\r\n " +
                    "   .fancy-display-form-wrapper .slidingDivClose {\r\n        float: right;\r\n      " +
                    "  font-size: large;\r\n    }\r\n\r\n    .fancy-display-form-wrapper .slidingDivHeader " +
                    "{\r\n        border-bottom: 1px solid #EEEEEE;\r\n        cursor: auto;\r\n        fon" +
                    "t-size: 1.4em;\r\n        padding-bottom: 5px;\r\n        padding-top: 5px;\r\n       " +
                    " font-family: Open Sans Regular !important;\r\n        color: #555555;\r\n    }\r\n\r\n " +
                    "   .fancy-display-form-wrapper .slidingDivAdd {\r\n        float: right;\r\n        " +
                    "left: 190px;\r\n        position: inherit;\r\n        top: 25px;\r\n    }\r\n\r\n    .fanc" +
                    "y-display-form-wrapper .listMainDiv {\r\n        float: left;\r\n        margin-righ" +
                    "t: 5px;\r\n    }\r\n\r\n    .fancyDisplayFormAssociatedItemsContextMenu {\r\n        lis" +
                    "t-style: none;\r\n        cursor: pointer;\r\n        position: absolute;\r\n    }\r\n</" +
                    "style>\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    $(function () {\r\n\r\n        Fanc" +
                    "yDispFormClient.fillWebPartData();\r\n\r\n        $(\".fancy-display-form-wrapper .di" +
                    "spFormExpandHeader\").click(function () {\r\n            $header = $(this);\r\n      " +
                    "      $content = $header.next();\r\n            $content.slideToggle(100, function" +
                    " () {\r\n            });\r\n            if ($(this).find(\"span:first\").hasClass(\"ico" +
                    "n-plus-circle-2\")) {\r\n                $(this).find(\"span:first\").removeClass(\"ic" +
                    "on-plus-circle-2\").addClass(\"icon-minus-circle-2\");\r\n                $(this).fin" +
                    "d(\"span:last\").text(\"hide\");\r\n            }\r\n            else {\r\n               " +
                    " $(this).find(\"span:first\").removeClass(\"icon-minus-circle-2\").addClass(\"icon-pl" +
                    "us-circle-2\");\r\n                $(this).find(\"span:last\").text(\"show\");\r\n       " +
                    "     }\r\n        });\r\n\r\n        $(\".dispFormExpandMore\").click(function () {\r\n   " +
                    "         $header = $(this);\r\n            $header.closest(\'tr\').next(\'.ShowMoreRo" +
                    "w\').toggle();\r\n        });\r\n    });\r\n\r\n    FancyDispFormClient = {\r\n\r\n        sh" +
                    "owItemUrl: function (weburl) {\r\n            $.ajax({\r\n                type: \"POS" +
                    "T\",\r\n                url: weburl,\r\n                success: function (ticket) {\r" +
                    "\n                    if (ticket.indexOf(\"General Error\") != 0) {\r\n              " +
                    "          var listInfo = ticket.split(\'|\');\r\n\r\n                        var viewS" +
                    "iteContentUrl = listInfo[0] + \"/_layouts/epmlive/gridaction.aspx?action=FancyDis" +
                    "pForm&list=\" + listInfo[3] + \"&field=\" + listInfo[1] + \"&LookupFieldList=\" + lis" +
                    "tInfo[2] + \"&Source=\" + document.location.href;\r\n                        var opt" +
                    "ions = { url: viewSiteContentUrl, showMaximized: true };\r\n                      " +
                    "  SP.SOD.execute(\'SP.UI.Dialog.js\', \'SP.UI.ModalDialog.showModalDialog\', options" +
                    ");\r\n                    }\r\n                    else {\r\n                        a" +
                    "lert(ticket);\r\n                    }\r\n                }\r\n            });\r\n      " +
                    "  },\r\n\r\n        showNewForm: function (weburl) {\r\n            var options = { ur" +
                    "l: weburl, showMaximized: false, dialogReturnValueCallback: function (dialogResu" +
                    "lt) { if (dialogResult == 1) { FancyDispFormClient.reFillWebPartData(); } } };\r\n" +
                    "            SP.SOD.execute(\'SP.UI.Dialog.js\', \'SP.UI.ModalDialog.showModalDialog" +
                    "\', options);\r\n        },\r\n\r\n        showItemPopup: function (siteurl, webid, lis" +
                    "tid, itemid) {\r\n            showSharePointPopup(siteurl + \'/_layouts/epmlive/gri" +
                    "daction.aspx?action=getcontextmenus&webid=\' + webid +\r\n                \'&listid=" +
                    "\' + listid + \'&ID=\' + itemid, null, false, true, null, {\r\n                    gr" +
                    "idId: \"myDiv\",\r\n                    rowId: \"myDiv\",\r\n                    col: \"m" +
                    "yDiv\"\r\n                }, 300, 400);\r\n        },\r\n\r\n        emptyFunction: funct" +
                    "ion () {\r\n        },\r\n\r\n        showSharePointPopup: function (url, title, allow" +
                    "Maximize, showClose, func, funcParams, width, height) {\r\n            if (allowMa" +
                    "ximize == null) allowMaximize = true;\r\n            if (showClose == null) showCl" +
                    "ose = true;\r\n            if (func == null) func = emptyFunction;\r\n\r\n            " +
                    "var options;\r\n\r\n            if (width !== undefined && height !== undefined) {\r\n" +
                    "                options = {\r\n                    title: title,\r\n                " +
                    "    allowMaximize: allowMaximize,\r\n                    showClose: showClose,\r\n  " +
                    "                  url: url,\r\n                    dialogReturnValueCallback: Func" +
                    "tion.createCallback(Function.createDelegate(null, func), funcParams),\r\n         " +
                    "           width: width,\r\n                    height: height\r\n                };" +
                    "\r\n            } else {\r\n                options = { title: title, allowMaximize:" +
                    " allowMaximize, showClose: showClose, url: url, dialogReturnValueCallback: Funct" +
                    "ion.createCallback(Function.createDelegate(null, func), funcParams) };\r\n        " +
                    "    }\r\n\r\n            SP.UI.ModalDialog.showModalDialog(options);\r\n        },\r\n\r\n" +
                    "        reFillWebPartData: function () {\r\n            window.setTimeout(\'FancyDi" +
                    "spFormClient.fillWebPartData()\', 2000);\r\n        },\r\n\r\n        fillWebPartData: " +
                    "function () {\r\n            $.ajax({\r\n                type: \"POST\",\r\n            " +
                    "    url: \"");
              @__w.Write(SPContext.Current.Web.Url);

            @__w.Write("/_vti_bin/WorkEngine.asmx/Execute\",\r\n                data: \"{Function : \'GetFancy" +
                    "FormAssociatedItems\' , Dataxml: \'<FancyFormAssociatedItems><FancyFormListID>");
                                                                                                                @__w.Write(SPContext.Current.ListId);

            @__w.Write("</FancyFormListID><FancyFormItemID>");
                                                                                                                                                                                @__w.Write(SPContext.Current.ItemId);

            @__w.Write("</FancyFormItemID></FancyFormAssociatedItems>\'}\",\r\n                contentType: \"" +
                    "application/json; charset=utf-8\",\r\n                dataType: \"json\",\r\n          " +
                    "      success: function (response) {\r\n\r\n                    $(\"#");
                @__w.Write(divFancyDispFormAssociatedItemsContent.ClientID);

            @__w.Write("\").html(\"\");\r\n                    $(\"#");
                @__w.Write(divFancyDispFormAssociatedItemsContent.ClientID);

            @__w.Write("\").html(response.d.toString().replace(\"<Result Status=\\\"0\\\">\", \"\").replace(\"</Res" +
                    "ult>\", \"\"));\r\n\r\n                    $(\".slidingDiv\").hide();\r\n\r\n                " +
                    "    var mouseX, mouseY, windowWidth, windowHeight;\r\n                    var popu" +
                    "pLeft, popupTop;\r\n                    $(document).mousemove(function (e) {\r\n    " +
                    "                    mouseX = e.pageX;\r\n                        mouseY = e.pageY;" +
                    "\r\n                        //To Get the relative position\r\n                      " +
                    "  if (this.offsetLeft != undefined)\r\n                            mouseX = e.page" +
                    "X - this.offsetLeft;\r\n                        if (this.offsetTop != undefined)\r\n" +
                    "                            mouseY = e.pageY; -this.offsetTop;\r\n\r\n              " +
                    "          if (mouseX < 0)\r\n                            mouseX = 0;\r\n            " +
                    "            if (mouseY < 0)\r\n                            mouseY = 0;\r\n\r\n        " +
                    "                windowWidth = $(window).width() + $(window).scrollLeft();\r\n     " +
                    "                   windowHeight = $(window).height() + $(window).scrollTop();\r\n " +
                    "                   });\r\n\r\n                    $(\'.listMainDiv .badge\').mouseente" +
                    "r(\r\n                        function () {\r\n                            $(\".slidi" +
                    "ngDiv\").hide();\r\n\r\n                            var currentSlidingDiv = $(this).p" +
                    "arent().parent().find(\".slidingDiv\");\r\n                            currentSlidin" +
                    "gDiv.show();\r\n\r\n                            var popupWidth = currentSlidingDiv.o" +
                    "uterWidth();\r\n                            var popupHeight = currentSlidingDiv.ou" +
                    "terHeight();\r\n\r\n                            if (mouseX + popupWidth > windowWidt" +
                    "h)\r\n                                popupLeft = mouseX - popupWidth;\r\n          " +
                    "                  else\r\n                                popupLeft = mouseX;\r\n\r\n " +
                    "                           if (mouseY + popupHeight > windowHeight)\r\n           " +
                    "                     popupTop = mouseY - popupHeight;\r\n                         " +
                    "   else\r\n                                popupTop = mouseY;\r\n\r\n                 " +
                    "           if (popupLeft < $(window).scrollLeft()) {\r\n                          " +
                    "      popupLeft = $(window).scrollLeft();\r\n                            }\r\n\r\n    " +
                    "                        if (popupTop < $(window).scrollTop()) {\r\n               " +
                    "                 popupTop = $(window).scrollTop();\r\n                            " +
                    "}\r\n\r\n                            if (popupLeft < 0 || popupLeft == undefined)\r\n " +
                    "                               popupLeft = 0;\r\n                            if (p" +
                    "opupTop < 0 || popupTop == undefined)\r\n                                popupTop " +
                    "= 0;\r\n\r\n                            currentSlidingDiv.offset({ top: popupTop, le" +
                    "ft: popupLeft });\r\n\r\n                            currentSlidingDiv.mouseenter(fu" +
                    "nction () {\r\n                                currentSlidingDiv.show();\r\n        " +
                    "                    });\r\n\r\n                            currentSlidingDiv.mousele" +
                    "ave(function () {\r\n                                window.setTimeout(function ()" +
                    " {\r\n                                    currentSlidingDiv.hide();\r\n             " +
                    "                   }, 2000);\r\n                            });\r\n                 " +
                    "       }\r\n                    );\r\n\r\n                    $(\"#");
                @__w.Write(divFancyDispFormAssociatedItemsContent.ClientID);

            @__w.Write(@""").mouseleave(function () {
                        window.setTimeout(function () {
                            $("".slidingDiv"").hide();
                        }, 2000);
                    });

                    var addContextualMenu = function () {
                        $("".fancyDisplayFormAssociatedItemsContextMenu"").each(function () {
                            window.epmLiveNavigation.addContextualMenu($(this), null, true, '-1', { ""delete"": ""FancyDispFormClient.reFillWebPartData"" });
                        });
                    };

                    window.ExecuteOrDelayUntilScriptLoaded(addContextualMenu, 'EPMLive.Navigation.js');
                }
            });
        }
    }
</script>

");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
