//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMLiveEnterprise {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ps-2013/PWA/_vti_bin/psi/customfields.asmx?wsdl")]
        public string EPMLivePS_WebSvcCustomFields_customfields {
            get {
                return ((string)(this["EPMLivePS_WebSvcCustomFields_customfields"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ps-2013/PWA/_vti_bin/psi/events.asmx?wsdl")]
        public string EPMLivePS_WebSvcEvents_events {
            get {
                return ((string)(this["EPMLivePS_WebSvcEvents_events"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ps-2013/PWA/_vti_bin/psi/loginwindows.asmx?wsdl")]
        public string EPMLivePS_WebSvcLoginWindows_loginwindows {
            get {
                return ((string)(this["EPMLivePS_WebSvcLoginWindows_loginwindows"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ps-2013/PWA/_vti_bin/psi/lookuptable.asmx?wsdl")]
        public string EPMLivePS_WebSvcLookupTables_lookuptable {
            get {
                return ((string)(this["EPMLivePS_WebSvcLookupTables_lookuptable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ps-2013/PWA/_vti_bin/psi/project.asmx?wsdl")]
        public string EPMLivePS_WebSvcProject_project {
            get {
                return ((string)(this["EPMLivePS_WebSvcProject_project"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ps-2013/PWA/_vti_bin/psi/queuesystem.asmx?wsdl")]
        public string EPMLivePS_WebSvcQueueSystem_queuesystem {
            get {
                return ((string)(this["EPMLivePS_WebSvcQueueSystem_queuesystem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ps-2013/PWA/_vti_bin/psi/resource.asmx?wsdl")]
        public string EPMLivePS_WebSvcResource_resource {
            get {
                return ((string)(this["EPMLivePS_WebSvcResource_resource"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ps-2013/PWA/_vti_bin/psi/statusing.asmx?wsdl")]
        public string EPMLivePS_WebSvcStatusing_statusing {
            get {
                return ((string)(this["EPMLivePS_WebSvcStatusing_statusing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ps-2013/PWA/_vti_bin/psi/wssinterop.asmx?wsdl")]
        public string EPMLivePS_WebSvcWssInterop_wssinterop {
            get {
                return ((string)(this["EPMLivePS_WebSvcWssInterop_wssinterop"]));
            }
        }
    }
}
