//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMLiveCore.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkEngineLookupPickerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkEngineLookupPickerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPMLiveCore.GlobalResources.WorkEngineLookupPickerResources", typeof(WorkEngineLookupPickerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchable columns:.
        /// </summary>
        internal static string lookupWithPickerChooseSearchFieldsLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerChooseSearchFieldsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Lookup with Picker.
        /// </summary>
        internal static string lookupWithPickerDescription {
            get {
                return ResourceManager.GetString("lookupWithPickerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup with Picker.
        /// </summary>
        internal static string lookupWithPickerDisplayName {
            get {
                return ResourceManager.GetString("lookupWithPickerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a column to show each of these additional fields:.
        /// </summary>
        internal static string lookupWithPickerEditorDependentColumnsLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorDependentColumnsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field has been deleted..
        /// </summary>
        internal static string lookupWithPickerEditorLookupFieldDeletedError {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorLookupFieldDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this column:.
        /// </summary>
        internal static string lookupWithPickerEditorLookupFieldLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorLookupFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get information from list:.
        /// </summary>
        internal static string lookupWithPickerEditorLookupListLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorLookupListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get information from site:.
        /// </summary>
        internal static string lookupWithPickerEditorLookupWebLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorLookupWebLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multiple values:.
        /// </summary>
        internal static string lookupWithPickerEditorMultiLookupLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorMultiLookupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascade delete.
        /// </summary>
        internal static string lookupWithPickerEditorRelationContraintsCascade {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorRelationContraintsCascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship behavior:.
        /// </summary>
        internal static string lookupWithPickerEditorRelationContraintsLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorRelationContraintsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string lookupWithPickerEditorRelationContraintsNone {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorRelationContraintsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict delete.
        /// </summary>
        internal static string lookupWithPickerEditorRelationContraintsRestricted {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorRelationContraintsRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the columns that you want to use for search in the picker dialog:.
        /// </summary>
        internal static string lookupWithPickerEditorSearchableColumnsLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerEditorSearchableColumnsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity rows (applies to multiselect mode):.
        /// </summary>
        internal static string lookupWithPickerEntityRowsLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerEntityRowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal search results:.
        /// </summary>
        internal static string lookupWithPickerMaxSearchResultsLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerMaxSearchResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begins with.
        /// </summary>
        internal static string lookupWithPickerOperatorBeginsWith {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string lookupWithPickerOperatorContains {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equals.
        /// </summary>
        internal static string lookupWithPickerOperatorEquals {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater than.
        /// </summary>
        internal static string lookupWithPickerOperatorGreaterThan {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater than or equal to.
        /// </summary>
        internal static string lookupWithPickerOperatorGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than.
        /// </summary>
        internal static string lookupWithPickerOperatorLessThan {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than or equal to.
        /// </summary>
        internal static string lookupWithPickerOperatorLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not equal.
        /// </summary>
        internal static string lookupWithPickerOperatorNotEqual {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of search results has been exeeded. Please refine your search..
        /// </summary>
        internal static string lookupWithPickerSearchResultExceededMessage {
            get {
                return ResourceManager.GetString("lookupWithPickerSearchResultExceededMessage", resourceCulture);
            }
        }
    }
}
