using System;
using System.Collections;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Text;
using EPMLiveEnterprise.WebSvcCustomFields;
using EPMLiveEnterprise.WebSvcLookupTables;
using EPMLiveEnterprise.WebSvcProject;
using EPMLiveEnterprise.WebSvcResource;
using EPMLiveEnterprise.WebSvcStatusing;
using EPMLiveEnterprise.WebSvcWssInterop;
using Microsoft.Office.Project.Server.Events;
using Microsoft.SharePoint;

namespace EPMLiveEnterprise
{
    internal partial class Publisher
    {
        private const string ResourceNames = "ResourceNames";
        private const string TaskCenter = "Task Center";
        private const string TransUid = "transuid";
        private const string TaskHierarchy = "TaskHierarchy";
        private const string IsAssignment = "IsAssignment";
        private const string Title = "Title";
        private const string TaskUid = "taskuid";
        private const string TaskOrder = "taskorder";
        private const string Summary = "Summary";
        private const string Notes = "Notes";
        private const string LastPublished = "LastPublished";
        private const string Wbs = "WBS";
        private const string AssignedTo = "AssignedTo";
        private const string ProjectText = "Project";
        private const int PubTypeOne = 1;
        private const int PubTypeTwo = 2;
        private const int PubTypeThree = 3;
        private const string DateTimeText = "DATETIME";
        private const string Duration = "DURATION";
        private const string NumberText = "NUMBER";
        private const string DateValue = "DATE_VALUE";
        private const string DurationValue = "DUR_VALUE";
        private const string NumberValue = "NUM_VALUE";
        private const string Currency = "CURRENCY";
        private const string BooleanText = "BOOLEAN";
        private const string FlagValue = "FLAG_VALUE";
        private const string TextId = "TEXT";
        private const string TextValue = "TEXT_VALUE";
        private const string Choice = "CHOICE";
        private const string CodeValue = "CODE_VALUE";
        private const string FieldCategoryThree = "3";
        private const string FieldCategoryTwo = "2";
        private const string FieldCategoryOne = "1";
        private const string TimeSheetId = "Timesheet";
        private const string LinkType = "LINK_TYPE";
        private const string TaskPredecessors = "TASK_PREDECESSORS";
        private const string TaskResnames = "TASK_RESNAMES";
        private const string TaskPctComp = "TASK_PCT_COMP";
        private const string PercentComplete = "PercentComplete";
        private const string TransUidText = "transuid";
        private const string IsProjectServer = "IsProjectServer";
        private const string ProjectGuid = "projectguid";
        private const string PublishToPwa = "PublishToPWA";
        private const string SharePointProject = "SharePointProject";
        private const string ProjectServerUrl = "ProjectServerURL";
        private const string ProjectCenter = "Project Center";
        private const string Member = "Member";
        private const string Visitor = "Visitor";
        private const string ResourceUid = "Res_UID";
        private const char FieldSplitChar = '#';
        private const string ResourceIsWindowsUser = "RES_IS_WINDOWS_USER";
        private const string WresAccount = "WRES_ACCOUNT";
        private const string ResourceName = "RES_NAME";
        private const string ResourceId = "Res_ID";
        private const string Slash = "/";

        private EventLog myLog = new EventLog("EPM Live", ".", "EPM Live Publisher");
        private Guid taskEntity = new Guid(Microsoft.Office.Project.Server.Library.EntityCollection.Entities.TaskEntity.UniqueId);
        private bool _disposed;
        private CustomFields pCf;
        private Resource pResource;
        private Project pService;
        private CustomFieldDataSet cfDs;
        private LookupTable psiLookupTable;
        private Statusing Statusing;
        private WssInterop pWssInterop;
        private string publishSiteUrl;
        private string projectServerUrl;
        private SPSite mySite;
        private SPWeb mySiteToPublish;
        private Guid projectGuid;
        private Guid mySiteGuid;
        private SqlConnection cn;
        private Hashtable hshCurTasks;
        private ArrayList arrDelTasks;
        private ArrayList arrDelNewTasks;
        private DataTable dtFieldsToPublish;
        private ArrayList arrFieldsToPublish;
        private ArrayList arrPJFieldsToPublish;
        private Hashtable hshTaskCenterFields;
        private Hashtable hshProjectCenterFields;
        private Hashtable hshTaskHierarchy;
        private ProjectWorkspaceSynch workspaceSynch;
        private Microsoft.Office.Project.Server.Library.PSContextInfo contextInfo;
        private ProjectPostPublishEventArgs eventArgs;
        private Guid lastTransUid;
        private ResourceDataSet rDs;
        private CustomFieldDataSet dsFields;
        private LookupTableDataSet dsLt;
        private string strTimesheetField = "";
        private StringBuilder sbErrors = new StringBuilder();
        private double pctComplete;
    }
}