//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPublisher2016.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/_vti_bin/epmlivepublisher.asmx")]
        public string ProjectPublisher2016_EPMLivePublisher_EPMLivePublisher {
            get {
                return ((string)(this["ProjectPublisher2016_EPMLivePublisher_EPMLivePublisher"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/_vti_bin/epmlivetimephased.asmx")]
        public string ProjectPublisher2016_EPMLiveTimePhased_EPMLiveTimePhased {
            get {
                return ((string)(this["ProjectPublisher2016_EPMLiveTimePhased_EPMLiveTimePhased"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/_vti_bin/lists.asmx")]
        public string ProjectPublisher2016_SPSLists_Lists {
            get {
                return ((string)(this["ProjectPublisher2016_SPSLists_Lists"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/_vti_bin/sitedata.asmx")]
        public string ProjectPublisher2016_SPSSiteData_SiteData {
            get {
                return ((string)(this["ProjectPublisher2016_SPSSiteData_SiteData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/_vti_bin/usergroup.asmx")]
        public string ProjectPublisher2016_SPSUserGroup_UserGroup {
            get {
                return ((string)(this["ProjectPublisher2016_SPSUserGroup_UserGroup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/_vti_bin/views.asmx")]
        public string ProjectPublisher2016_SPSViews_Views {
            get {
                return ((string)(this["ProjectPublisher2016_SPSViews_Views"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://activation.epmlive.com/activationservice/service.asmx")]
        public string ProjectPublisher2016_WSactivation_Service {
            get {
                return ((string)(this["ProjectPublisher2016_WSactivation_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/wssservice/service.asmx")]
        public string ProjectPublisher2016_WSSService_Service {
            get {
                return ((string)(this["ProjectPublisher2016_WSSService_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/_vti_bin/integration.asmx")]
        public string ProjectPublisher2016_EPMLiveIntegration_Integration {
            get {
                return ((string)(this["ProjectPublisher2016_EPMLiveIntegration_Integration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008:8080/portfolioengine421/services/webservice.asmx")]
        public string ProjectPublisher2016_EPKWebService_WebService {
            get {
                return ((string)(this["ProjectPublisher2016_EPKWebService_WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/_vti_bin/authentication.asmx")]
        public string ProjectPublisher2016_SPSAuthentication_Authentication {
            get {
                return ((string)(this["ProjectPublisher2016_SPSAuthentication_Authentication"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/_vti_bin/workengine.asmx")]
        public string ProjectPublisher2016_EPMLiveWorkEngine_WorkEngineAPI {
            get {
                return ((string)(this["ProjectPublisher2016_EPMLiveWorkEngine_WorkEngineAPI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jasondev2008/_vti_bin/portfolioengine.asmx")]
        public string ProjectPublisher2016_EPMLivePortfolioEngine_PortfolioEngineAPI {
            get {
                return ((string)(this["ProjectPublisher2016_EPMLivePortfolioEngine_PortfolioEngineAPI"]));
            }
        }
    }
}
