pipeline {
    agent {
        node {
            label 'epmlive-win'
            customWorkspace "c:\\jenkins\\build"
        }
    }
    options {
        skipDefaultCheckout true
    }
	
    parameters {
        string(name: 'Version', defaultValue: '7.2.6.x', description: 'Version to set if new Release build is going to be triggered (x is replaced with new Release build number)')
        string(name: 'TargetHost', defaultValue: '10.137.18.88', description: 'Target host to deploy to')
        string(name: 'UserName', defaultValue: 'epmldev\\farmadmin', description: 'Name of the user to use when connecting PowerShell to the target host')
        string(name: 'Password', defaultValue: 'Pass@word1', description: 'Password used along with the User name')
		string(name: 'AppUrl', defaultValue: 'http://qaepmlive6', description: 'SharePoint application url for deployment')
    }
    stages {
        stage('Preparing Release') {
            steps { 
                timestamps {
                    script {
                        env.RELEASE_BRANCH = currentBuild.getProjectName()
						echo 'Triggering Release build job...'
						def releaseBuild = build(
							job: "../EPML-RC/${env.RELEASE_BRANCH}",
							wait: true,
							parameters: [
								[$class: 'StringParameterValue', name: 'Version', value: params.Version.replace('x', env.BUILD_NUMBER)]
							]
						)
						env.RELEASE_BRANCH_BUILD = releaseBuild.getNumber()
                        echo "Release Branch Build #${env.RELEASE_BRANCH_BUILD}"
                    }
                }
            }
        }
		stage('Deploy Quality') {
			steps {
				timestamps {
					script {
						echo 'Triggering Deploy job...'
						env.DEPLOY_BRANCH = currentBuild.getProjectName()
						build(
							job: "../EPML-Deploy/${env.DEPLOY_BRANCH}", 
							wait: true,
							parameters: [
								[$class: 'StringParameterValue', name: 'TargetHost', value: params.TargetHost],
								[$class: 'StringParameterValue', name: 'UserName', value: params.UserName],
								[$class: 'StringParameterValue', name: 'Password', value: params.Password],
								[$class: 'StringParameterValue', name: 'FullHostName', value: params.AppUrl]
							]
						)
					}
				}
			}
		}
    }
}
