//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMLive.OnlineLicensing.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderHistory()
        {
            this.OrderDetailHistories = new HashSet<OrderDetailHistory>();
        }
    
        public System.Guid history_id { get; set; }
        public System.Guid order_id { get; set; }
        public int account_ref { get; set; }
        public string plimusReferenceNumber { get; set; }
        public int quantity { get; set; }
        public Nullable<int> projects { get; set; }
        public Nullable<System.DateTime> activation { get; set; }
        public System.DateTime expiration { get; set; }
        public int plimusAccountId { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<System.DateTime> dtcreated { get; set; }
        public Nullable<System.Guid> poId { get; set; }
        public Nullable<System.Guid> crmuid { get; set; }
        public string crmorderid { get; set; }
        public Nullable<System.Guid> crmorderuid { get; set; }
        public Nullable<System.Guid> crminvoiceuid { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string contractid { get; set; }
        public Nullable<int> billingsystem { get; set; }
        public Nullable<int> product_id { get; set; }
        public int reason { get; set; }
        public string reason_comment { get; set; }
        public Nullable<int> diskspace { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailHistory> OrderDetailHistories { get; set; }
        public virtual LicenseProduct LicenseProduct { get; set; }
    }
}
