//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMLive.OnlineLicensing.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailHistory
    {
        public System.Guid history_id { get; set; }
        public System.Guid order_detail_id { get; set; }
        public System.Guid order_id { get; set; }
        public Nullable<int> detail_type_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual OrderHistory OrderHistory { get; set; }
        public virtual DetailType DetailType { get; set; }
    }
}
