//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMLive.OnlineLicensing.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwActiveOrder
    {
        public System.Guid order_id { get; set; }
        public int account_ref { get; set; }
        public string plimusReferenceNumber { get; set; }
        public int quantity { get; set; }
        public Nullable<int> diskspace { get; set; }
        public System.DateTime expiration { get; set; }
        public int plimusAccountId { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<System.DateTime> dtcreated { get; set; }
        public Nullable<System.Guid> poId { get; set; }
        public Nullable<System.Guid> crmuid { get; set; }
        public string crmorderid { get; set; }
    }
}
