IF NOT EXISTS(	SELECT * FROM sys.indexes WHERE name='IDX_ACCOUNTUSER_ACCOUNTID_DELETED' AND object_id = OBJECT_ID('dbo.[ACCOUNT_USERS]'))
BEGIN
	CREATE NONCLUSTERED INDEX IDX_ACCOUNTUSER_ACCOUNTID_DELETED
    ON [dbo].[ACCOUNT_USERS] ([account_id],[deleted])
    INCLUDE ([account_user_guid],[user_id])
END
