IF EXISTS(SELECT * FROM sys.indexes WHERE name='GA_IDX_TSITEMHOURS_2' AND object_id = OBJECT_ID('dbo.[TSITEMHOURS]'))
BEGIN
    DROP INDEX GA_IDX_TSITEMHOURS_2 ON dbo.[TSITEMHOURS]
END
GO

CREATE NONCLUSTERED INDEX [GA_IDX_TSITEMHOURS_2] ON dbo.[TSITEMHOURS]
(
        [TS_ITEM_UID] ASC
)
INCLUDE
(
        [TS_ITEM_DATE],
        [TS_ITEM_HOURS],
        [TS_ITEM_TYPE_ID]
)
WITH (STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO

IF EXISTS(SELECT * FROM sys.indexes WHERE name='GA_IDX_TSITEM_3' AND object_id = OBJECT_ID('dbo.[TSITEM]'))
BEGIN
    DROP INDEX GA_IDX_TSITEM_3 ON dbo.[TSITEM]
END
GO

CREATE NONCLUSTERED INDEX [GA_IDX_TSITEM_3] ON [dbo].[TSITEM]
(
	[TS_UID] ASC
)
INCLUDE
(
        [TS_ITEM_UID],
        [WEB_UID],
        [LIST_UID],
        [ITEM_TYPE],
        [ITEM_ID],
        [TITLE],
        [PROJECT],
        [PROJECT_ID],
        [PROJECT_LIST_UID],
        [LIST]
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
