IF EXISTS(SELECT * FROM sys.indexes WHERE name='GA_IDX_TSITEMHOURS_2' AND object_id = OBJECT_ID('dbo.[TSITEMHOURS]'))
BEGIN
    DROP INDEX GA_IDX_TSITEMHOURS_2 ON dbo.[TSITEMHOURS]
END
GO

CREATE NONCLUSTERED INDEX [GA_IDX_TSITEMHOURS_2] ON dbo.[TSITEMHOURS]
(
        [TS_ITEM_UID] ASC,
        [TS_ITEM_TYPE_ID] ASC
)
INCLUDE ([TS_ITEM_HOURS], [TS_ITEM_DATE])
WITH (STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
